wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_01_-_the_swedish_rhapsody.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_02_-_counting_cia.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_03_-_counting_control.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_04_-_phonetic_alphabet_nato.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_05_-_5_dashes.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_06_-_the_lincolnshire_poacher_mi5.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_07_-_gong_station_chimes.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_08_-_dfd_21.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_09_-_ready_ready_15728.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_10_-_bugle.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_11_-_5_note_version_czech_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_12_-_three_note_odditiy.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_14_-_counting_station_spanish.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_15_-_english_lady_00000_ending.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_16_-_attencion_3_finals.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_17_-_4_note_rising_scale.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_18_-_ciocirlia.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_19_-_czech_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_20_-_letter_ys.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_21_-_2_letter_el.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_22_-_5_dashes.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Irdial/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_23_-_2_letter_rk.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_01_-_nnn_french.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_02_-_strich.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_03_-_dfd21_dfc37.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_04_-_drums_and_trumpets.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_05_-_nnn_english.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_07_-_nnn_german.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_08_-_the_russian_man_d-va_northern_russian_voice.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_09_-_phonetic_alphabet_nato.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_10_-_spanish_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_11_-_strich_english.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_12_-_2_letter_nu.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_13_-_g3_strich.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_14_-_yt.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_15_-_5_dashes.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_16_-_german_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_18_-_english_man_german_and_german_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_19_-_german_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_20_-_chinese_numbers.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_23_-_english_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_24_-_german_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_25_-_phonetic_alphabet_nato.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_26_-_phonetic_alphabet_nato.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_27_-_nancy_adam_susan.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_28_-_counting_control.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_29_-_nancy_adam_susan_male.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_30_-_cherry_ripe.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_31_-_russian_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_32_-_russian_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_33_-_nnn_english.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_34_-_frank_young_peter.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_36_-_russian_counting_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_37_-_olx_irdial.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_38_-_6_tones.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_39_-_high_pitch_polytone.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_40_-_high_pitch_polytone.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_41_-_high_pitch_polytone.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_42_-_high_pitch_polytone.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_01_-_ready_ready.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_02_-_iran_iraq_jamming_efficacy_testting.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_03_-_english_lady.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_04_-_english_lady_jammed.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_05_-_english_man_version_1.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_06_-_english_man_version_3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_07_-_english_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_09_-_magnetic_fields_different_voice.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_10_-_oblique.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_11_-_nnn_old_incarnation.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_12_-_5_dashes_i_say_again.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_13_-_2_letter_kg.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_14_-_4_figure_counting_10_rough_tones.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_15_-_2_voices_in_one_transmission.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_16_-_tyrolean_music_station.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_17_-_3_note_interval_signal.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_18_-_10_rough_tones.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_19_-_achtung.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_20_-_a.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_21_-_voice_sample_1-10.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_22_-_voice_rapid_dots_irdial.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_23_-_strich_with_rare_message.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_24_-_hier_ist_dfc_seben_und_dreizig.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_25_-_2_letter_pn.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_26_-_sample_count.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_27_-_2_letter_vo.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_28_-_2_letter_hk.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_29_-_2_letter_dm.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_30_-_8_note_rising_scale.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_31_-_spruchnummer_1.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_33_-_random_pop.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_34_-_nomer_101.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_35_-_okno_okno_onko.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_36_-_nomer_198.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_37_-_723_papaqui.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_38_-_298.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_39_-_815.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_40_-_167.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_41_-_moscow_coup_attempt.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_01_-_russian_man_complete.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_02_-_2_yt.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_04_-_preska.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_05_-_cherta.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_06_-_count_in_russian.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_07_-_count_in_russian_different_voice.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_08_-_1-10_announcement.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_09_-_1-10_announcement_female.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_10_-_counting_in_polish.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_11_-_konec_konec.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_12_-_pozor.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_13_-_russian_lady_test_count_and_message.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_14_-_russian_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_15_-_spanish_lady_2_finals.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_16_-_spanish_counting.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_17_-_spanish_counting_4_figure_groups.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_18_-_spanish_man.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_19_-_spanish_lady_00000_ending.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_21_-_eastern_music_station.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_22_-_eastern_music_station_different.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_23_-_unidentified_chinese_station.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_24_-_nnn_french_early_version.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_25_-_nnn_hungarian.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_26_-_wiskey_tango_viente_y_uno.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_27_-_the_crackle.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_28_-_the_backwards_music_station.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_29_-_faders.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_30_-_workshop.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_31_-_the_pip.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_32_-_the_buzzer.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_33_-_m1.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_34_-_m1b.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_35_-_m2.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_36_-_m3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_37_-_m3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_39_-_m3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_40_-_m3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_41_-_41_m3.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_42_-_m3a.mp3
wget https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/The_Conet_Project/The_Conet_Project/The_Conet_Project_-_43_-_m3b.mp3
